title: MatSE580 Guest Lectures
description: one guest lecture for MatSE580 at PSU to cover pure element CALPHAD modeling
show_downloads: "true"
markdown: GFM

navigation:
  name_over_title: false
  strip_par: true
  sanitize: true
  h_min: 1
  h_max: 4

remote_theme: Bilal2453/cayman-docs
plugins:
- jekyll-remote-theme 
